name: Deploy Lambda

on:
  push:
    branches:
      - homolog
      - main
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Ambiente de deploy'
        required: true
        type: choice
        options:
          - homolog
          - producao

jobs:
  deploy-homolog:
    name: Deploy Homologação
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/homolog' || (github.event_name == 'workflow_dispatch' && github.event.inputs.ambiente == 'homolog')
    environment: homolog
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - uses: aws-actions/setup-sam@v2
      - name: Build e Deploy
        run: |
          sam build
          sam deploy \
            --stack-name oficina-lambda-homolog \
            --s3-bucket oficina-sam-artifacts-302789973247 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              DBHost=${{ secrets.DB_HOST }} \
              DBPort=${{ secrets.DB_PORT }} \
              DBName=${{ secrets.DB_NAME }} \
              DBUser=${{ secrets.DB_USER }} \
              DBPassword=${{ secrets.DB_PASSWORD }} \
              JWTSecret=${{ secrets.JWT_SECRET }}

  deploy-producao:
    name: Deploy Produção
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.ambiente == 'producao')
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      - uses: aws-actions/setup-sam@v2
      - name: Build e Deploy
        run: |
          sam build
          sam deploy \
            --stack-name oficina-lambda-prod \
            --s3-bucket oficina-sam-artifacts-302789973247 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              DBHost=${{ secrets.DB_HOST }} \
              DBPort=${{ secrets.DB_PORT }} \
              DBName=${{ secrets.DB_NAME }} \
              DBUser=${{ secrets.DB_USER }} \
              DBPassword=${{ secrets.DB_PASSWORD }} \
              JWTSecret=${{ secrets.JWT_SECRET }}
